### ISSUE TITLE
Examples are sometimes innacurate 

### ISSUE THREAD

**Issue by 3rr3s3v3n** [davidsiaw/luacppinterface#17]
Hi everyone!
I'm trying to use this interface, and I'm following your examples to better understand how to use that. I sadly found out that some tutorials are wrong (I mean they don't compile or they crash at runtime).
For example:
#include \<fstream\>
#include \<streambuf\>
#include \<string\>
#include \<iostream\>
#include \<luacppinterface.h\>

int main()
{
  std::ifstream file("config.lua");
  std::string script((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
  Lua lua;
  int width = lua.GetGlobalEnvironment.Get<int>("width");    // get the width
  int height = lua.GetGlobalEnvironment.Get<int>("height");  // get the height
  std::string windowTitle = lua.GetGlobalEnvironment.Get<std::string>("windowTitle");

  return 0;
}

* GetGlobalEnvironment is a function, but it seems to be a static variable of Lua type;
* config.lua file isn't loaded, while no RunScript was called (I suppose).

Can you fix it, please?
Thank you in advance!

**Comment by davidsiaw** [comment]
You are right! I just fixed the docs. thanks for letting me know!

**Comment by 3rr3s3v3n** [comment]
Great! :D
Thank you again ;)
