### ISSUE TITLE
Create LuaUserdata from template

### ISSUE THREAD

**Issue by tesla9** [davidsiaw/luacppinterface#32]
hi, maybe I understand something incorrectly, but I am unable to create LuaUserdata from template class.

Here is the example:
class:
```c++
template <typename T>
class TestClass
{
	T mA;
public:
	TestClass(T a): mA(a) {}
};
```
code:
```c++
LuaTable testClass = mLua.CreateTable();
auto makeTestClass = lua.CreateFunction< LuaUserdata<TestClass<int>(int)> >(
[&](int prm)
{
LuaUserdata<TestClass<int>> newTestClass = mLua.CreateUserdata<TestClass<int>>(new TestClass<int>(prm));
return newTestClass;
}
);
testClass.Set("new", makeTestClass);
```

and error:
error: no instance of function template "CreateFunction" matches the argument list
            argument types are: (lambda [](int)->LuaUserdata<TestClass<int>>)
            object type is: Lua

Is there any other way to do that? When TestClass is not a template everything works perfect.

**Comment by davidsiaw** [comment]
I assume you wanted a function that takes an `int` and returns a `LuaUserdata< TestClass<int> >`

In this case your function signature is wrong. Instead of 

`LuaUserdata<  TestClass<int>(int)  >`

it should be 

`LuaUserdata<  TestClass<int>  >(int)`

(note the triangular brackets' placements)

**Comment by tesla9** [comment]
Thank you very much David, I had to be tired ;)
