### ISSUE TITLE
function overloading

### ISSUE THREAD

**Issue by tesla9** [davidsiaw/luacppinterface#34]
I try to create function adding two images. I have images in `LuaUserdata<Image<uint>>` and `LuaUsersata<Image<uchar>>` . When it try to overload lua function  'Add', I've got 'segmentation fault'. 
When I define 'Add' function taking  `LuaUserdata<Image<uchar>>` it works perfectly, the same for uint. However when I declare both function together, I have an error in run time.
Here is the code:
```
	template<typename SIG>
	void RegisterFunction(std::function<SIG> func, const string & funcName)
	{
    	auto global = mLua.GetGlobalEnvironment();
	global.Set(funcName, mLua.CreateFunction<SIG>(func));
	}
```
...
```
RegisterFunction< void( LuaUserdata<Image<uint>>, LuaUserdata<Image<uint>>, LuaUserdata<Image<uint>>  )>( Add<uint>, "Add" );

RegisterFunction< void( LuaUserdata<Image<uchar>>, LuaUserdata<Image<uchar>>, LuaUserdata<Image<uchar>>  )>(Add<uchar>,"Add" );
```

**Comment by davidsiaw** [comment]
I have images in LuaUserdata> and LuaUsersata> 

I assume these are all different LuaUserdata<A> and LuaUserdata<B>  ?
